### ISSUE TITLE
Add Record Evolution to the list of adopters

### ISSUE THREAD

**Issue by ZornitsaD** [eclipse-theia/theia-website#233]
Hi, Record Evolution here. We are developing our low-code application enablement platform and are using Theia for our cloud IDE. Could we be included in the list of adopters? 

More about us here: https://www.record-evolution.de/en/home-en/

And our IoT & AI platform can be accessed from here: https://studio.record-evolution.com/en/explore

Our logo: ![logo_record_evolution_single (1)](https://user-images.githubusercontent.com/53559158/140045942-e6ab655e-1ef2-4720-98a6-8b1bf3c10b60.png)

Thanks!!

**Comment by vince-fugnitto** [comment]
@ZornitsaD glad to hear from you and the community would be happy to add your company's name to the website!

In order to add information to the website, you can prepare a pull-request to add your company to the list of adopters following a similar request which was done in the [past](https://github.com/eclipse-theia/theia-website/pull/100/files).

The idea would be to modify the following to include your company's information:

https://github.com/eclipse-theia/theia-website/blob/26a13cb06887550de1c4a81c510f8fe094d5d636/src/utils/data.js#L40-L45

The company image would be added under `src/resources`.

In addition, if you have a screenshot of your tool you'd like to add you can modify the following:

https://github.com/eclipse-theia/theia-website/blob/426f56c43635f8fb9027adbfe118f9b9dd3df480/src/utils/data.js#L103

**Comment by JonasHelming** [comment]
I see you on the home page, so I am closing this...
