### ISSUE TITLE
How to start hosted instance in Authoring Theia Plug-ins?

### ISSUE THREAD

**Issue by ggodlewski** [eclipse-theia/theia-website#313]
I'm trying to create hello world plugin from tutorial https://theia-ide.org/docs/authoring_plugins/

Currently I'm on the step "Executing the Plug-in"
1. I Hit F1, Hosted Plugin: start instance
2. Select directory
3. In the output there is an error:

```
yarn run v1.22.19

error Couldn't find a package.json file in "/home/gg/bin"

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://user-images.githubusercontent.com/818238/184383380-485a710f-83a2-4b1a-aab7-cd0253c111d7.png)

`/home/gg/bin` is a directory from which I'm starting current `TheiaBlueprint.AppImage`

Why is it looking for some `package.json` in this directory?

Also screenshots look like they are from some old version of Theia.

**Comment by JonasHelming** [comment]
Thank you for reporting this. I can reproduce the issue, we will discuss a fix.
In the meantime: Is there a particular reason why you want to create a Theia plugin and not either a VS Code extension or a Theia extension (see [here](https://theia-ide.org/docs/extensions/)).
Most adopters use VS Code extensions or Theia extensions. We should probably make this more clear in the documentation. Thank you again for the report!

@vince-fugnitto @paul-marechal @tsmaeder

**Comment by JonasHelming** [comment]
Please see [here](https://github.com/eclipse-theia/theia/discussions/11579#discussioncomment-3421462) for the follow up discussion about updating the documentation.

**Comment by ggodlewski** [comment]
Thank you. The reason I started with plugin was this website. The pros clearly show that using plugins is better than extensions.
I wanted to use Theia instead of Electron to create my project because I seemed that it would be faster. This is the 3rd issue I reported regarding the website. It seems very outdated or maybe I maybe it's just my learning path?

**Comment by planger** [comment]
Hi @ggodlewski, thank you very much for your feedback! It is highly appreciated. :+1: 

The Theia plugin mechanism you were attempting to use is something quite special and the documentation on this mechanism is indeed a bit dusty, I guess because it isn't used a lot. The two main [extension mechanisms of Theia](https://theia-ide.org/docs/extensions), which are much more commonly used, are:
1. [Theia extensions](https://theia-ide.org/docs/authoring_extensions)
2. [VS Code extensions](https://code.visualstudio.com/api)

Whether to use (1) or (2) really depends a lot on the use case. One is not clearly better than the other. While the Theia extensions mechanism (1) is much more powerful and makes it much easier to write native custom views and editors, the VS Code extension mechanism (2) is a bit simpler to use -- except for custom views and editors -- and enables using your extension in Theia and VS Code, however it is very limited in what you can do. For an in-depth discussion of this topic, please confer to a [dedicated blog post on this topic](https://eclipsesource.com/blogs/2021/03/24/vs-code-extensions-vs-theia-extensions/amp/).

Thanks again for taking the time to report issues for improving the documentation! Not many new adopters are doing that, but it is a very valuable contribution and eventually helps improving the onboarding experience of many new adopters to come significantly!

Based on your feedback, we've opened two tickets (https://github.com/eclipse-theia/theia-website/issues/314 and https://github.com/eclipse-theia/theia-website/issues/316), which we are addressing soon. :factory_worker:
