### ISSUE TITLE
Add page about authoring VS Code extensions

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-website#316]
Can be a very short description and directly link to VS Code API documentation.
Ideally, the Theia extension generator can generate a template.
Should be linked here: https://theia-ide.org/docs/extensions/
Should be in the main menu under "using Theia" => Authoring VS Code extensions

@planger

**Comment by planger** [comment]
Should this new documentation replace the existing [Authoring Plug-ins](https://theia-ide.org/docs/authoring_plugins/) page?
We can remove it in a subsequent step, but I'm asking because if both are shown, I guess an explanation would be required what's the difference, which can be omitted if we only show the page for VS Code extensions.

**Comment by JonasHelming** [comment]
https://github.com/eclipse-theia/theia-website/pull/315

**Comment by JonasHelming** [comment]
#315 should go in asap and then we replace it with this when ready
